{% set version = "1.0.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: sd
  version: {{ version }}

source:
  url: https://github.com/chmln/sd/archive/v{{ version }}.tar.gz
  sha256: 2adc1dec0d2c63cbffa94204b212926f2735a59753494fca72c3cfe4001d472f

build:
  number: 0
  script:
    - RUSTFLAGS="-Clink-args=-Wl,-L$PREFIX/lib" cargo install --path . --root "$PREFIX"  # [unix]
    - cargo install --path . --root "%LIBRARY_PREFIX%"                                   # [win]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}   # [unix]
    - {{ native }}binutils  # [win]
    - cargo-bundle-licenses

test:
  commands:
    - sd --help

about:
  home: https://github.com/chmln/sd
  license: MIT
  license_family: MIT
  summary: Intuitive find & replace CLI (sed alternative)
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - jonashaag
