{% set version = "0.7.6" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: sd
  version: {{ version }}

source:
  url: https://github.com/chmln/sd/archive/v{{ version }}.tar.gz
  sha256: faf33a97797b95097c08ebb7c2451ac9835907254d89863b10ab5e0813b5fe5f

build:
  number: 1
  script:
    - RUSTFLAGS="-Clink-args=-Wl,-L$PREFIX/lib" cargo install --path . --root "$PREFIX"  # [unix]
    - cargo install --path . --root "%LIBRARY_PREFIX%"                                   # [win]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}   # [unix]
    - {{ native }}binutils  # [win]
    - cargo-bundle-licenses

test:
  commands:
    - sd --help

about:
  home: https://github.com/chmln/sd
  license: MIT
  license_family: MIT
  summary: Intuitive find & replace CLI (sed alternative)
  license_file:
    - LICENSE
    - - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - jonashaag
